(function(root){
  const LANGUAGES={
    ar:{name:'ערבית',native:'العربية',code:'AR',primaryNote:'תעתיק עברי',secondaryNote:'כתב ערבי'},
    it:{name:'איטלקית',native:'Italiano',code:'IT',primaryNote:'איטלקית',secondaryNote:''},
    ru:{name:'רוסית',native:'Русский',code:'RU',primaryNote:'תעתיק לטיני',secondaryNote:'קירילית'},
    es:{name:'ספרדית',native:'Español',code:'ES',primaryNote:'ספרדית',secondaryNote:''}
  };

  const TOPIC_META={
    basics:{name:'בסיס ושיחה',icon:'💬',description:'שלום, תודה, שאלות קצרות ושיחה יומיומית'},
    family:{name:'משפחה ואנשים',icon:'👥',description:'משפחה, חברים ותיאור אנשים'},
    food:{name:'אוכל ושתייה',icon:'🍽️',description:'הזמנה, רעב, צמא ומסעדה'},
    directions:{name:'רחוב וכיוונים',icon:'🧭',description:'איפה, ימינה, שמאלה, קרוב ורחוק'},
    time:{name:'זמן ויום יום',icon:'🕒',description:'היום, מחר, עכשיו, מוקדם ומאוחר'},
    sport:{name:'ספורט וכדורעף',icon:'🏐',description:'אימון, משחק, קפיצה, כדור וניצחון'}
  };

  const COURSES={
    ar:{
      basics:{words:[['hello','مرحبا','מַרְחַבַּא','שלום'],['thanks','شكرا','שֻכְּרַן','תודה'],['please','لو سمحت','לַו סַמַחְת','בבקשה / סליחה'],['yes','نعم','נַעַם','כן'],['no','لا','לַא','לא'],['how','كيف','כִּיף','איך'],['where','وين','וֵין','איפה'],['why','ليش','לֵיש','למה']],sentences:[['howare','كيفك؟','כִּיפַכּ?','מה שלומך?','אתה פוגש חבר ושואל לשלומו.'],['fine','أنا منيح، شكرا.','אַנַא מְנִיח, שֻכְּרַן.','אני בסדר, תודה.','עונים שמרגישים טוב.'],['wherego','وين بدك تروح؟','וֵין בַּדַּכּ תְרוּח?','לאן אתה רוצה ללכת?','שואלים חבר לאן הוא רוצה ללכת.'],['why','ليش؟','לֵיש?','למה?','מבקשים הסבר קצר.']]},
      family:{words:[['father','أب','אַבּ','אבא'],['mother','أم','אֻם','אמא'],['brother','أخ','אַח׳','אח'],['sister','أخت','אֻח׳ת','אחות'],['friend','صاحب','סַאחֶבּ','חבר'],['child','ولد','וַלַד','ילד'],['family','عيلة','עֵילֶה','משפחה'],['name','اسم','אִסֶם','שם']],sentences:[['myname','اسمي بن.','אִסְמִי בֶּן.','קוראים לי בן.','מציגים את עצמך.'],['myfriend','هذا صاحبي.','הַאדַא סַאחְבִּי.','זה החבר שלי.','מציגים חבר.'],['familyhome','عيلتي بالبيت.','עֵילְתִי בַּלְבֵּית.','המשפחה שלי בבית.','מספרים איפה המשפחה.'],['sister','عندي أخت.','עִנְדִי אֻח׳ת.','יש לי אחות.','מספרים על המשפחה.']]},
      food:{words:[['water','مي','מַי','מים'],['coffee','قهوة','קַהְוֶה','קפה'],['food','أكل','אַכֶּל','אוכל'],['hungry','جعان','ג׳ַעַאן','רעב'],['thirsty','عطشان','עַטְשַאן','צמא'],['want','بدي','בַּדִּי','אני רוצה'],['bill','حساب','חְסַאבּ','חשבון'],['good','طيب','טַיֶבּ','טעים / טוב']],sentences:[['wantwater','بدي أشرب مي.','בַּדִּי אַשְרַבּ מַי.','אני רוצה לשתות מים.','מבקשים מים.'],['coffee','بدي قهوة، لو سمحت.','בַּדִּי קַהְוֶה, לַו סַמַחְת.','אני רוצה קפה, בבקשה.','מזמינים קפה.'],['hungry','أنا جعان.','אַנַא ג׳ַעַאן.','אני רעב.','אומרים שאתה רעב.'],['bill','الحساب، لو سمحت.','אֶלְחְסַאבּ, לַו סַמַחְת.','חשבון, בבקשה.','מבקשים חשבון.']]},
      directions:{words:[['home','بيت','בֵּית','בית'],['road','طريق','טַרִיק','דרך'],['here','هون','הוֹן','כאן'],['there','هناك','הְנַאכּ','שם'],['near','قريب','קַרִיבּ','קרוב'],['far','بعيد','בַּעִיד','רחוק'],['right','يمين','יַמִין','ימין'],['left','شمال','שְמַאל','שמאל']],sentences:[['where','وين الطريق؟','וֵין אֶ־טַרִיק?','איפה הדרך?','שואלים איפה הדרך.'],['near','البيت قريب.','אֶל־בֵּית קַרִיבּ.','הבית קרוב.','אומרים שהבית קרוב.'],['right','روح يمين.','רוּח יַמִין.','לך ימינה.','נותנים כיוון.'],['here','أنا هون.','אַנַא הוֹן.','אני כאן.','אומרים איפה אתה.']]},
      time:{words:[['today','اليوم','אִלְיוֹם','היום'],['tomorrow','بكرة','בֻּכְּרַה','מחר'],['now','هسا','הַסַּא','עכשיו'],['time','وقت','וַקְת','זמן'],['later','بعدين','בַּעְדֵין','אחר כך'],['early','بكير','בַּכִּיר','מוקדם'],['late','متأخر','מְתְאַחֶר','מאוחר'],['day','يوم','יוֹם','יום']],sentences:[['notime','ما عندي وقت.','מַא עִנְדִי וַקְת.','אין לי זמן.','אומרים שאין זמן.'],['tomorrow','بشوفك بكرة.','בְּשוּפַכּ בֻּכְּרַה.','אראה אותך מחר.','נפרדים עד מחר.'],['now','هسا بدي أروح.','הַסַּא בַּדִּי אַרוּח.','עכשיו אני רוצה ללכת.','אומרים שרוצים לצאת עכשיו.'],['later','بعدين منحكي.','בַּעְדֵין מְנִחְכִּי.','נדבר אחר כך.','דוחים שיחה לאחר כך.']]},
      sport:{words:[['ball','طابة','טַאבֶּה','כדור'],['game','لعبة','לַעְבֶּה','משחק'],['training','تمرين','תַמְרִין','אימון'],['team','فريق','פַרִיק','קבוצה'],['jump','نط','נַט','קפיצה'],['win','فوز','פוֹז','ניצחון'],['coach','مدرب','מְדַרֶבּ','מאמן'],['strong','قوي','קַוִי','חזק']],sentences:[['training','عندي تمرين اليوم.','עִנְדִי תַמְרִין אִלְיוֹם.','יש לי אימון היום.','מספרים שיש אימון היום.'],['team','فريقنا قوي.','פַרִיקְנַא קַוִי.','הקבוצה שלנו חזקה.','מדברים על הקבוצה.'],['ball','هات الطابة.','הַאת אֶ־טַאבֶּה.','תביא את הכדור.','מבקשים את הכדור.'],['win','بدنا فوز.','בִּדְנַא פוֹז.','אנחנו רוצים ניצחון.','לפני משחק.']]}
    },
    it:{
      basics:{words:[['hello','ciao','','שלום / ביי'],['thanks','grazie','','תודה'],['please','per favore','','בבקשה'],['yes','sì','','כן'],['no','no','','לא'],['how','come','','איך'],['where','dove','','איפה'],['why','perché','','למה']],sentences:[['howare','Come stai?','','מה שלומך?','אתה פוגש חבר ושואל לשלומו.'],['fine','Sto bene, grazie.','','אני בסדר, תודה.','עונים שמרגישים טוב.'],['wherego','Dove vuoi andare?','','לאן אתה רוצה ללכת?','שואלים לאן רוצים ללכת.'],['why','Perché?','','למה?','מבקשים הסבר קצר.']]},
      family:{words:[['father','padre','','אבא'],['mother','madre','','אמא'],['brother','fratello','','אח'],['sister','sorella','','אחות'],['friend','amico','','חבר'],['child','bambino','','ילד'],['family','famiglia','','משפחה'],['name','nome','','שם']],sentences:[['myname','Mi chiamo Ben.','','קוראים לי בן.','מציגים את עצמך.'],['friend','Questo è il mio amico.','','זה החבר שלי.','מציגים חבר.'],['familyhome','La mia famiglia è a casa.','','המשפחה שלי בבית.','מספרים איפה המשפחה.'],['sister','Ho una sorella.','','יש לי אחות.','מספרים על המשפחה.']]},
      food:{words:[['water','acqua','','מים'],['coffee','caffè','','קפה'],['food','cibo','','אוכל'],['hungry','affamato','','רעב'],['thirsty','assetato','','צמא'],['want','voglio','','אני רוצה'],['bill','conto','','חשבון'],['good','buono','','טעים / טוב']],sentences:[['water','Voglio bere acqua.','','אני רוצה לשתות מים.','מבקשים מים.'],['coffee','Vorrei un caffè, per favore.','','אני רוצה קפה, בבקשה.','מזמינים קפה.'],['hungry','Ho fame.','','אני רעב.','אומרים שאתה רעב.'],['bill','Il conto, per favore.','','חשבון, בבקשה.','מבקשים חשבון.']]},
      directions:{words:[['home','casa','','בית'],['road','strada','','דרך'],['here','qui','','כאן'],['there','lì','','שם'],['near','vicino','','קרוב'],['far','lontano','','רחוק'],['right','destra','','ימין'],['left','sinistra','','שמאל']],sentences:[['where','Dov’è la strada?','','איפה הדרך?','שואלים איפה הדרך.'],['near','La casa è vicina.','','הבית קרוב.','אומרים שהבית קרוב.'],['right','Vai a destra.','','לך ימינה.','נותנים כיוון.'],['here','Sono qui.','','אני כאן.','אומרים איפה אתה.']]},
      time:{words:[['today','oggi','','היום'],['tomorrow','domani','','מחר'],['now','adesso','','עכשיו'],['time','tempo','','זמן'],['later','dopo','','אחר כך'],['early','presto','','מוקדם'],['late','tardi','','מאוחר'],['day','giorno','','יום']],sentences:[['notime','Non ho tempo.','','אין לי זמן.','אומרים שאין זמן.'],['tomorrow','Ci vediamo domani.','','נתראה מחר.','נפרדים עד מחר.'],['now','Adesso voglio andare.','','עכשיו אני רוצה ללכת.','אומרים שרוצים לצאת עכשיו.'],['later','Parliamo dopo.','','נדבר אחר כך.','דוחים שיחה.']]},
      sport:{words:[['ball','palla','','כדור'],['game','partita','','משחק'],['training','allenamento','','אימון'],['team','squadra','','קבוצה'],['jump','salto','','קפיצה'],['win','vittoria','','ניצחון'],['coach','allenatore','','מאמן'],['strong','forte','','חזק']],sentences:[['training','Ho allenamento oggi.','','יש לי אימון היום.','מספרים שיש אימון היום.'],['team','La nostra squadra è forte.','','הקבוצה שלנו חזקה.','מדברים על הקבוצה.'],['ball','Dammi la palla.','','תן לי את הכדור.','מבקשים את הכדור.'],['win','Vogliamo vincere.','','אנחנו רוצים לנצח.','לפני משחק.']]}
    },
    ru:{
      basics:{words:[['hello','привет','privet','שלום'],['thanks','спасибо','spasibo','תודה'],['please','пожалуйста','pozhaluysta','בבקשה'],['yes','да','da','כן'],['no','нет','net','לא'],['how','как','kak','איך'],['where','где','gde','איפה'],['why','почему','pochemu','למה']],sentences:[['howare','Как дела?','Kak dela?','מה שלומך?','אתה פוגש חבר ושואל לשלומו.'],['fine','Всё хорошо, спасибо.','Vsyo khorosho, spasibo.','הכול בסדר, תודה.','עונים שמרגישים טוב.'],['wherego','Куда ты хочешь пойти?','Kuda ty khochesh poyti?','לאן אתה רוצה ללכת?','שואלים לאן רוצים ללכת.'],['why','Почему?','Pochemu?','למה?','מבקשים הסבר קצר.']]},
      family:{words:[['father','отец','otets','אבא'],['mother','мама','mama','אמא'],['brother','брат','brat','אח'],['sister','сестра','sestra','אחות'],['friend','друг','drug','חבר'],['child','ребёнок','rebyonok','ילד'],['family','семья','semya','משפחה'],['name','имя','imya','שם']],sentences:[['myname','Меня зовут Бен.','Menya zovut Ben.','קוראים לי בן.','מציגים את עצמך.'],['friend','Это мой друг.','Eto moy drug.','זה החבר שלי.','מציגים חבר.'],['familyhome','Моя семья дома.','Moya semya doma.','המשפחה שלי בבית.','מספרים איפה המשפחה.'],['sister','У меня есть сестра.','U menya yest sestra.','יש לי אחות.','מספרים על המשפחה.']]},
      food:{words:[['water','вода','voda','מים'],['coffee','кофе','kofe','קפה'],['food','еда','yeda','אוכל'],['hungry','голодный','golodnyy','רעב'],['thirsty','хочу пить','khochu pit','צמא'],['want','хочу','khochu','אני רוצה'],['bill','счёт','schyot','חשבון'],['good','вкусно','vkusno','טעים']],sentences:[['water','Я хочу воды.','Ya khochu vody.','אני רוצה מים.','מבקשים מים.'],['coffee','Я хочу кофе, пожалуйста.','Ya khochu kofe, pozhaluysta.','אני רוצה קפה, בבקשה.','מזמינים קפה.'],['hungry','Я голодный.','Ya golodnyy.','אני רעב.','אומרים שאתה רעב.'],['bill','Счёт, пожалуйста.','Schyot, pozhaluysta.','חשבון, בבקשה.','מבקשים חשבון.']]},
      directions:{words:[['home','дом','dom','בית'],['road','дорога','doroga','דרך'],['here','здесь','zdes','כאן'],['there','там','tam','שם'],['near','близко','blizko','קרוב'],['far','далеко','daleko','רחוק'],['right','направо','napravo','ימין'],['left','налево','nalevo','שמאל']],sentences:[['where','Где дорога?','Gde doroga?','איפה הדרך?','שואלים איפה הדרך.'],['near','Дом близко.','Dom blizko.','הבית קרוב.','אומרים שהבית קרוב.'],['right','Иди направо.','Idi napravo.','לך ימינה.','נותנים כיוון.'],['here','Я здесь.','Ya zdes.','אני כאן.','אומרים איפה אתה.']]},
      time:{words:[['today','сегодня','segodnya','היום'],['tomorrow','завтра','zavtra','מחר'],['now','сейчас','seychas','עכשיו'],['time','время','vremya','זמן'],['later','потом','potom','אחר כך'],['early','рано','rano','מוקדם'],['late','поздно','pozdno','מאוחר'],['day','день','den','יום']],sentences:[['notime','У меня нет времени.','U menya net vremeni.','אין לי זמן.','אומרים שאין זמן.'],['tomorrow','Увидимся завтра.','Uvidimsya zavtra.','נתראה מחר.','נפרדים עד מחר.'],['now','Сейчас я хочу идти.','Seychas ya khochu idti.','עכשיו אני רוצה ללכת.','אומרים שרוצים לצאת עכשיו.'],['later','Поговорим потом.','Pogovorim potom.','נדבר אחר כך.','דוחים שיחה.']]},
      sport:{words:[['ball','мяч','myach','כדור'],['game','игра','igra','משחק'],['training','тренировка','trenirovka','אימון'],['team','команда','komanda','קבוצה'],['jump','прыжок','pryzhok','קפיצה'],['win','победа','pobeda','ניצחון'],['coach','тренер','trener','מאמן'],['strong','сильный','silnyy','חזק']],sentences:[['training','У меня тренировка сегодня.','U menya trenirovka segodnya.','יש לי אימון היום.','מספרים שיש אימון היום.'],['team','Наша команда сильная.','Nasha komanda silnaya.','הקבוצה שלנו חזקה.','מדברים על הקבוצה.'],['ball','Дай мне мяч.','Day mne myach.','תן לי את הכדור.','מבקשים את הכדור.'],['win','Мы хотим победить.','My khotim pobedit.','אנחנו רוצים לנצח.','לפני משחק.']]}
    },
    es:{
      basics:{words:[['hello','hola','','שלום'],['thanks','gracias','','תודה'],['please','por favor','','בבקשה'],['yes','sí','','כן'],['no','no','','לא'],['how','cómo','','איך'],['where','dónde','','איפה'],['why','por qué','','למה']],sentences:[['howare','¿Cómo estás?','','מה שלומך?','אתה פוגש חבר ושואל לשלומו.'],['fine','Estoy bien, gracias.','','אני בסדר, תודה.','עונים שמרגישים טוב.'],['wherego','¿Adónde quieres ir?','','לאן אתה רוצה ללכת?','שואלים לאן רוצים ללכת.'],['why','¿Por qué?','','למה?','מבקשים הסבר קצר.']]},
      family:{words:[['father','padre','','אבא'],['mother','madre','','אמא'],['brother','hermano','','אח'],['sister','hermana','','אחות'],['friend','amigo','','חבר'],['child','niño','','ילד'],['family','familia','','משפחה'],['name','nombre','','שם']],sentences:[['myname','Me llamo Ben.','','קוראים לי בן.','מציגים את עצמך.'],['friend','Este es mi amigo.','','זה החבר שלי.','מציגים חבר.'],['familyhome','Mi familia está en casa.','','המשפחה שלי בבית.','מספרים איפה המשפחה.'],['sister','Tengo una hermana.','','יש לי אחות.','מספרים על המשפחה.']]},
      food:{words:[['water','agua','','מים'],['coffee','café','','קפה'],['food','comida','','אוכל'],['hungry','hambriento','','רעב'],['thirsty','sed','','צמא'],['want','quiero','','אני רוצה'],['bill','cuenta','','חשבון'],['good','rico','','טעים']],sentences:[['water','Quiero beber agua.','','אני רוצה לשתות מים.','מבקשים מים.'],['coffee','Quiero un café, por favor.','','אני רוצה קפה, בבקשה.','מזמינים קפה.'],['hungry','Tengo hambre.','','אני רעב.','אומרים שאתה רעב.'],['bill','La cuenta, por favor.','','חשבון, בבקשה.','מבקשים חשבון.']]},
      directions:{words:[['home','casa','','בית'],['road','calle','','רחוב / דרך'],['here','aquí','','כאן'],['there','allí','','שם'],['near','cerca','','קרוב'],['far','lejos','','רחוק'],['right','derecha','','ימין'],['left','izquierda','','שמאל']],sentences:[['where','¿Dónde está la calle?','','איפה הרחוב?','שואלים איפה הדרך.'],['near','La casa está cerca.','','הבית קרוב.','אומרים שהבית קרוב.'],['right','Ve a la derecha.','','לך ימינה.','נותנים כיוון.'],['here','Estoy aquí.','','אני כאן.','אומרים איפה אתה.']]},
      time:{words:[['today','hoy','','היום'],['tomorrow','mañana','','מחר'],['now','ahora','','עכשיו'],['time','tiempo','','זמן'],['later','después','','אחר כך'],['early','temprano','','מוקדם'],['late','tarde','','מאוחר'],['day','día','','יום']],sentences:[['notime','No tengo tiempo.','','אין לי זמן.','אומרים שאין זמן.'],['tomorrow','Nos vemos mañana.','','נתראה מחר.','נפרדים עד מחר.'],['now','Ahora quiero ir.','','עכשיו אני רוצה ללכת.','אומרים שרוצים לצאת עכשיו.'],['later','Hablamos después.','','נדבר אחר כך.','דוחים שיחה.']]},
      sport:{words:[['ball','pelota','','כדור'],['game','partido','','משחק'],['training','entrenamiento','','אימון'],['team','equipo','','קבוצה'],['jump','salto','','קפיצה'],['win','victoria','','ניצחון'],['coach','entrenador','','מאמן'],['strong','fuerte','','חזק']],sentences:[['training','Tengo entrenamiento hoy.','','יש לי אימון היום.','מספרים שיש אימון היום.'],['team','Nuestro equipo es fuerte.','','הקבוצה שלנו חזקה.','מדברים על הקבוצה.'],['ball','Dame la pelota.','','תן לי את הכדור.','מבקשים את הכדור.'],['win','Queremos ganar.','','אנחנו רוצים לנצח.','לפני משחק.']]}
    }
  };

  function normaliseWord(code, topicId, raw){return {id:`${code}-${topicId}-${raw[0]}`,code,topic:topicId,target:raw[1],pron:raw[2]||'',he:raw[3]};}
  function normaliseSentence(code, topicId, raw){return {id:`${code}-${topicId}-s-${raw[0]}`,code,topic:topicId,target:raw[1],pron:raw[2]||'',he:raw[3],scenario:raw[4]||''};}
  function course(code,topicId){const c=COURSES[code]||COURSES.ar;const t=c[topicId]||c.basics;return {words:t.words.map(w=>normaliseWord(code,topicId,w)),sentences:t.sentences.map(s=>normaliseSentence(code,topicId,s))};}
  function validLanguage(code){return LANGUAGES[code]?code:'ar';}
  function validTopic(id){return TOPIC_META[id]?id:'basics';}
  function primary(code,item){if(code==='ar'||code==='ru')return item.pron||item.transliteration||item.target;return item.target;}
  function secondary(code,item){return code==='ar'||code==='ru'?item.target:'';}
  function loadState(){const fallback={completedByDate:{},seenWords:{},wordStatus:{},mistakes:{},selectedTopicByLanguage:{}};try{const p=JSON.parse(localStorage.getItem('my-center-languages-v1')||'{}');return {...fallback,...p,completedByDate:p.completedByDate||{},seenWords:p.seenWords||{},wordStatus:p.wordStatus||{},mistakes:p.mistakes||{},selectedTopicByLanguage:p.selectedTopicByLanguage||{}};}catch{return fallback;}}
  function saveState(state){localStorage.setItem('my-center-languages-v1',JSON.stringify(state));}
  function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
  function rememberWords(state,code,topicId,words){words.forEach(w=>{if(!state.seenWords[w.id])state.seenWords[w.id]={id:w.id,code,topic:topicId,target:w.target,transliteration:w.pron,pron:w.pron,hebrew:w.he,he:w.he,category:TOPIC_META[topicId].name,firstSeen:today()};if(!state.wordStatus[w.id])state.wordStatus[w.id]='new';});saveState(state);}
  function completedToday(state){return state.completedByDate[today()]||[];}
  function setCompleted(state,code,value=true){const set=new Set(completedToday(state));value?set.add(code):set.delete(code);state.completedByDate[today()]=[...set];saveState(state);}
  function markMistake(state,key,payload){const current=state.mistakes[key]||{count:0};state.mistakes[key]={...current,...payload,key,count:(current.count||0)+1,lastSeen:today()};saveState(state);}
  function clearMistake(state,key){delete state.mistakes[key];saveState(state);}
  function clearMistakesForLanguage(state,code){Object.keys(state.mistakes).forEach(k=>{if(state.mistakes[k]?.code===code)delete state.mistakes[k];});saveState(state);}
  function seenForLanguage(state,code){return Object.values(state.seenWords||{}).filter(x=>x&&x.code===code).map(x=>({id:x.id,code:x.code,topic:x.topic||'',target:x.target||'',pron:x.pron||x.transliteration||'',he:x.he||x.hebrew||'',category:x.category||''}));}
  function hash(text){let h=2166136261;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
  function shuffled(list,seedText){const a=[...list];let seed=hash(seedText);for(let i=a.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
  function options(correct,pool,count,seedText,keyFn=x=>x){const others=pool.filter(x=>keyFn(x)!==keyFn(correct));return shuffled([correct,...shuffled(others,seedText+'o').slice(0,Math.max(0,count-1))],seedText+'f');}
  function qs(){const p=new URLSearchParams(location.search);return {lang:validLanguage(p.get('lang')),topic:validTopic(p.get('topic'))};}

  root.LanguageCore={LANGUAGES,TOPIC_META,COURSES,course,validLanguage,validTopic,primary,secondary,loadState,saveState,today,rememberWords,completedToday,setCompleted,markMistake,clearMistake,clearMistakesForLanguage,seenForLanguage,shuffled,options,qs};
})(window);
