function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function statusMeta(status){const m={canon:{label:'✅ קאנון',className:'canon'},developing:{label:'📝 בפיתוח',className:'developing'},idea:{label:'💡 הצעה',className:'idea'},parked:{label:'🗄️ בצד',className:'parked'},archived:{label:'🗄️ ארכיון',className:'parked'}};return m[status]||m.idea;}
function characterName(id){return (typeof window!=='undefined'?window.RAIKA_DATA:null)?.characters?.find(c=>c.id===id)?.title||id;}
function searchableText(item){return [item.title,item.summary,item.role,item.thinking,item.placement,item.why,item.opens,...(item.tags||[]),...(item.characters||[]),...(item.traits||[]),...(item.wants||[]),...(item.fears||[]),...(item.beliefs||[]),...(item.contradictions||[])].join(' ').toLowerCase();}
function filterItems(items,q='',status='all',type='all'){q=String(q).trim().toLowerCase();return items.filter(i=>(!q||searchableText(i).includes(q))&&(status==='all'||i.status===status)&&(type==='all'||i.type===type));}
function writersRoomVisibleItems(items=[]){return items.filter(i=>i.status==='idea'||i.status==='parked');}
function tagsHtml(tags=[]){return tags.length?`<div class="pill-row raika-tags">${tags.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div>`:'';}
function charactersHtml(ids=[]){return ids.length?`<div class="raika-links"><b>דמויות:</b> ${ids.map(id=>`<a href="#characters" data-character-link="${esc(id)}">${esc(characterName(id))}</a>`).join(' · ')}</div>`:'';}
function detailsList(title,values){if(!values||(Array.isArray(values)&&!values.length))return'';const a=Array.isArray(values)?values:[values];return `<details><summary>${esc(title)}</summary><ul class="list">${a.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></details>`;}
function itemCardHtml(item){const meta=statusMeta(item.status);const extra=[item.role?`<div class="meta">${esc(item.role)}</div>`:'',charactersHtml(item.characters),item.placement?`<details><summary>מיקום מוצע בסיפור</summary><p>${esc(item.placement)}</p></details>`:'',item.why?`<details><summary>למה זה מתאים?</summary><p>${esc(item.why)}</p></details>`:'',item.opens?`<details><summary>מה זה יכול לפתוח?</summary><p>${esc(item.opens)}</p></details>`:'',detailsList('רצונות',item.wants),detailsList('פחדים',item.fears),detailsList('אמונות וערכים',item.beliefs),detailsList('סתירות פנימיות',item.contradictions),item.thinking?`<details><summary>צורת חשיבה</summary><p>${esc(item.thinking)}</p></details>`:''].join('');const link=item.feedPage?`<div class="card-actions"><a class="btn small" href="${esc(item.feedPage)}">פתח עמוד ←</a></div>`:'';return `<article class="card writer-card status-${meta.className}" data-status="${esc(item.status)}"><div class="writer-card-head"><span class="status-badge status-${meta.className}">${meta.label}</span>${item.order?`<span class="scene-number">${esc(item.order)}</span>`:''}</div><h3>${esc(item.title)}</h3>${item.summary?`<p class="meta writer-summary">${esc(item.summary)}</p>`:''}${extra}${tagsHtml(item.tags)}${link}</article>`;}
function sceneTextHtml(i){return esc(i.fullText||i.summary||'טקסט הסצנה יתווסף בהמשך').replace(/\n/g,'<br>');}
function sceneDetailHtml(i){const m=statusMeta(i.status),img=i.image?`<img class="scene-detail-image" src="${esc(i.image)}" alt="${esc(i.title)}" style="display:block;width:100%;height:auto;border-radius:16px;border:1px solid var(--line,#e8dfcf)">`:`<div class="scene-detail-image-placeholder" style="min-height:220px;display:flex;align-items:center;justify-content:center;text-align:center;border:1px dashed #cbbfdc;border-radius:16px;background:#f7f2fc;color:#786d88;font-weight:700">נעלה בהמשך</div>`;return `<div class="scene-detail-dialog" role="dialog" aria-modal="true" aria-label="${esc(i.title)}" style="position:relative;width:min(760px,100%);max-height:90vh;overflow:auto;background:var(--card,#fffdf8);border:1px solid var(--line,#e8dfcf);border-radius:22px;padding:22px;box-shadow:0 18px 60px rgba(0,0,0,.22)"><button class="scene-detail-close" type="button" aria-label="סגירת סצנה" style="position:absolute;left:14px;top:12px;border:1px solid var(--line,#e8dfcf);background:var(--card,#fffdf8);border-radius:999px;width:36px;height:36px;font-size:24px;cursor:pointer">×</button><div class="writer-card-head"><span class="status-badge status-${m.className}">${m.label}</span>${i.order?`<span class="scene-number">סצנה ${esc(i.order)}</span>`:''}</div><h2>${esc(i.title)}</h2><div class="scene-detail-text" style="margin:16px 0;line-height:1.9;font-size:16px">${sceneTextHtml(i)}</div><div class="scene-detail-media" style="margin-top:18px">${img}</div></div>`;}
function sceneCardHtml(i){return `<div class="scene-entry" data-scene-id="${esc(i.id)}" role="button" tabindex="0" aria-label="פתיחת סצנה מלאה: ${esc(i.title)}" style="cursor:pointer"><div class="scene-line"></div>${itemCardHtml(i)}</div>`;}
function openSceneDetail(i){document.getElementById('scene-detail-modal')?.remove();const modal=document.createElement('div');modal.id='scene-detail-modal';modal.className='scene-detail-modal';modal.style.cssText='position:fixed;inset:0;z-index:1000;background:rgba(31,31,31,.58);display:flex;align-items:center;justify-content:center;padding:18px';modal.innerHTML=sceneDetailHtml(i);document.body.appendChild(modal);const prev=document.body.style.overflow;document.body.style.overflow='hidden';const close=()=>{document.body.style.overflow=prev;modal.remove();document.removeEventListener('keydown',key)};const key=e=>{if(e.key==='Escape')close()};modal.querySelector('.scene-detail-close')?.addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',key);}
function getFilterState(){return{query:document.getElementById('raika-search')?.value||'',status:document.getElementById('raika-status-filter')?.value||'all',type:document.getElementById('raika-type-filter')?.value||'all'};}
function renderCollection(id,items,cardFn=itemCardHtml,empty='לא נמצאו פריטים'){const el=document.getElementById(id);if(!el)return;const s=getFilterState(),f=filterItems(items,s.query,s.status,s.type);el.innerHTML=f.length?f.map(cardFn).join(''):`<div class="card meta">${empty}</div>`;}
function currentRaikaSectionId(sections,scrollY=0,offset=0){if(!sections?.length)return'';const t=Number(scrollY)+Number(offset);let cur=sections[0].id;for(const s of sections){if(Number(s.top)<=t)cur=s.id;else break}return cur;}
function renderCharacters(d){renderCollection('characters-grid',d.characters)}function renderScenes(d){renderCollection('scenes-grid',[...d.scenes].sort((a,b)=>(a.order||999)-(b.order||999)),sceneCardHtml)}function renderPlotlines(d){renderCollection('plotlines-grid',d.plotlines)}function renderHistory(d){renderCollection('history-grid',d.history)}function renderWorld(d){renderCollection('world-grid',d.world)}function renderRelationships(d){renderCollection('relationships-grid',d.relationships)}function renderIdeas(d){renderCollection('ideas-grid',writersRoomVisibleItems(d.ideas))}
function renderStats(d){const el=document.getElementById('raika-stats');if(el)el.innerHTML=`<span>🎬 ${d.scenes.filter(x=>x.status==='canon').length} סצנות קאנון</span><span>👥 ${d.characters.length} דמויות</span><span>🧭 ${d.plotlines.length} קווי עלילה</span><span>💡 ${writersRoomVisibleItems(d.ideas).length} רעיונות בחדר הכותבים</span>`;}
function renderAll(){const d=window.RAIKA_DATA;if(!d)return;renderCharacters(d);renderScenes(d);renderPlotlines(d);renderHistory(d);renderWorld(d);renderRelationships(d);renderIdeas(d);renderStats(d);}
function ensureSavedNavLink(){const nav=document.querySelector('.raika-section-nav');if(!nav)return;let a=nav.querySelector('a[href="raika-saved.html"]');if(!a){a=document.createElement('a');a.href='raika-saved.html';a.textContent='📌 שמורים';nav.appendChild(a)}if(location.pathname.endsWith('raika-saved.html')){nav.querySelectorAll('a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}}
function initRaikaSectionNav(){const ids=['characters','scenes','plotlines','history','world','relationships','writers-room'],links=[...document.querySelectorAll('.raika-section-nav a[href^="#"]')];if(!links.length)return;const update=()=>{const secs=ids.map(id=>document.getElementById(id)).filter(Boolean).map(el=>({id:el.id,top:el.offsetTop}));const active=currentRaikaSectionId(secs,window.scrollY,(document.querySelector('.raika-sticky-tools')?.offsetHeight||0)+24);links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')===`#${active}`))};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update();}
function initRaikaWritersRoom(){ensureSavedNavLink();['raika-search','raika-status-filter','raika-type-filter'].forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener(el.tagName==='INPUT'?'input':'change',renderAll)});document.getElementById('clear-raika-filters')?.addEventListener('click',()=>{for(const [id,v] of [['raika-search',''],['raika-status-filter','all'],['raika-type-filter','all']]){const el=document.getElementById(id);if(el)el.value=v}renderAll()});const grid=document.getElementById('scenes-grid'),open=e=>{if(e.target.closest('a,button'))return;const entry=e.target.closest('[data-scene-id]'),item=window.RAIKA_DATA?.scenes?.find(s=>s.id===entry?.dataset.sceneId);if(item)openSceneDetail(item)};grid?.addEventListener('click',open);grid?.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(e)}});renderAll();initRaikaSectionNav();}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initRaikaWritersRoom);else initRaikaWritersRoom();}
if(typeof module!=='undefined')module.exports={statusMeta,filterItems,writersRoomVisibleItems,itemCardHtml,sceneCardHtml,sceneDetailHtml,currentRaikaSectionId};