const RFU={state:null,observer:null,started:false};
function rfuEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function rfuTypeLabel(type){return ({relationship:'🔗 קשר',consequence:'➡️ השלכה',secret:'🤫 סוד',comedy:'😂 קומדיה',missing_beat:'🕳️ רגע חסר',underused_character:'👤 דמות',worldbuilding:'🌍 עולם',legacy:'🧬 מורשת',antagonist:'🦹 יריב',school:'🏫 יום-יום',training:'🥋 אימון',wild_card:'🌩️ רעיון פרוע',dialogue:'💬 דיאלוג',perspective:'🪞 נקודת מבט',plot_seed:'🌱 זרע לעלילה',what_if:'❓ מה אם?',scene:'🎬 סצנה'})[type]||'💡 רעיון';}
function rfuErrorText(e){if(e?.code==='ai_not_configured')return 'ה־AI לא מחובר כרגע. בינתיים אני מציג רעיונות מקומיים מתוך עולם ראיקה.';if(e?.code==='openai_401')return 'מפתח ה־OpenAI של האתר אינו תקף. בינתיים מוצגים רעיונות מקומיים.';if(e?.code==='openai_429')return 'שירות ה־AI הגיע כרגע למגבלת מכסה או חיוב. בינתיים מוצגים רעיונות מקומיים.';return `${e?.message||'לא הצלחתי לטעון רעיונות AI.'} בינתיים מוצגים רעיונות מקומיים.`;}
function rfuCardHtml(card){const locked=RFU.state.locked.has(String(card.id));const why=card.why_it_may_work?`<details><summary>למה זה יכול לעבוד?</summary><p>${rfuEsc(card.why_it_may_work)}</p></details>`:'';const placement=card.suggested_placement?`<details><summary>איפה זה יכול להיכנס?</summary><p>${rfuEsc(card.suggested_placement)}</p></details>`:'';return `<article class="raika-feed-card${locked?' is-locked':''}" data-rf-card="${rfuEsc(card.id)}"><div class="raika-feed-card-head"><span class="meta">${rfuTypeLabel(card.card_type)}</span>${locked?'<span class="status-badge status-idea">נשמר/בפיתוח</span>':''}</div><h4>${rfuEsc(card.title)}</h4><p>${rfuEsc(card.body)}</p>${why}${placement}<div class="card-actions raika-feed-actions"><button class="btn small" data-rf-action="save">💾 שמור</button><button class="btn small" data-rf-action="like">❤️ אהבתי</button><button class="btn small" data-rf-action="more">🔄 עוד כזה</button><button class="btn small" data-rf-action="discuss">💬 בוא נדבר</button><button class="btn small" data-rf-action="develop">✍️ פתח לפיתוח</button><button class="btn small" data-rf-action="scene">🎬 הפוך לסצנה</button><button class="btn small" data-rf-action="less">🚫 פחות כאלה</button><button class="btn small" data-rf-action="hide">הסתר</button></div><div class="meta raika-feed-card-error" data-rf-error></div></article>`;}
function rfuRender(){const list=document.getElementById('raika-feed-list');if(!list||!RFU.state)return;const visible=RFU.state.cards.filter(c=>!RFU.state.hidden.has(String(c.id)));list.innerHTML=visible.map(rfuCardHtml).join('')||'<div class="meta">עוד רגע יופיעו כאן רעיונות.</div>';document.getElementById('raika-feed-loading')?.classList.toggle('hidden',!RFU.state.loading);const err=document.getElementById('raika-feed-error');if(err){err.innerHTML=RFU.state.error?`${rfuEsc(RFU.state.error)} <button class="btn small" type="button" data-rf-retry>נסה שוב AI</button>`:'';err.classList.toggle('hidden',!RFU.state.error);}}
function rfuRecentSignatures(){return RFU.state.cards.map(c=>c.signature).filter(Boolean).slice(-80);}
function rfuFallback(count){return window.RaikaFeedContext?.buildLocalFallbackCards(window.RAIKA_DATA||{},{count,seen:rfuRecentSignatures()})||[];}
function rfuShown(cards){for(const card of cards||[])if(card?.id&&!card.fallback)window.RaikaFeedClient?.feedback(card.id,'shown',{card_type:card.card_type}).catch(()=>{});}
async function rfuLoadMore({count=8}={}){const S=window.RaikaCreativeFeedState;if(!RFU.state||!S.canLoadMore(RFU.state)||!window.RaikaPrivate?.authorized)return;RFU.state=S.setLoading(RFU.state,true);rfuRender();try{const r=await RaikaFeedClient.generate({count,recentSignatures:rfuRecentSignatures()});const cards=r.cards||[];RFU.state=S.appendCards(RFU.state,cards);RFU.state=S.setError(RFU.state,'');rfuShown(cards);}catch(e){const cards=rfuFallback(count);RFU.state=S.appendCards(RFU.state,cards);RFU.state=S.setError(RFU.state,rfuErrorText(e));if(!cards.length)RFU.state=S.setExhausted(RFU.state,true);}finally{RFU.state=S.setLoading(RFU.state,false);rfuRender();}}
async function rfuSurprise(){const S=window.RaikaCreativeFeedState;if(!RFU.state||RFU.state.loading||!window.RaikaPrivate?.authorized)return;RFU.state=S.setLoading(RFU.state,true);rfuRender();try{const r=await RaikaFeedClient.generate({count:10,recentSignatures:rfuRecentSignatures()});const cards=r.cards||[];RFU.state=S.replaceUnlockedCards(RFU.state,cards);RFU.state=S.setError(RFU.state,'');rfuShown(cards);}catch(e){const cards=rfuFallback(10);RFU.state=S.replaceUnlockedCards(RFU.state,cards);RFU.state=S.setError(RFU.state,rfuErrorText(e));}finally{RFU.state=S.setLoading(RFU.state,false);rfuRender();}}
function rfuGetCard(id){return RFU.state?.cards.find(c=>String(c.id)===String(id))||null;}
function rfuMarkLocked(id){RFU.state=RaikaCreativeFeedState.lockCard(RFU.state,id);rfuRender();}
function rfuHide(id){RFU.state=RaikaCreativeFeedState.hideCard(RFU.state,id);rfuRender();}
function rfuInsertAfter(id,cards){RFU.state=RaikaCreativeFeedState.insertCardsAfter(RFU.state,id,cards);rfuShown(cards);rfuRender();}
function rfuShowCardError(id,message=''){const el=document.querySelector(`[data-rf-card="${CSS.escape(String(id))}"] [data-rf-error]`);if(el)el.textContent=message?`⚠️ ${message}`:'';}
function rfuInit(){const host=document.getElementById('raika-feed');if(!host||RFU.started||!window.RaikaCreativeFeedState)return;RFU.started=true;RFU.state=RaikaCreativeFeedState.createFeedState();document.getElementById('raika-feed-surprise')?.addEventListener('click',rfuSurprise);host.addEventListener('click',e=>{if(e.target.closest('[data-rf-retry]')){RFU.state=RaikaCreativeFeedState.setError(RFU.state,'');RFU.state=RaikaCreativeFeedState.setExhausted(RFU.state,false);rfuLoadMore({count:8});}});const sentinel=document.getElementById('raika-feed-sentinel');if('IntersectionObserver'in window&&sentinel){RFU.observer=new IntersectionObserver(entries=>{if(entries.some(x=>x.isIntersecting))rfuLoadMore({count:RFU.state.cards.length?8:10});},{rootMargin:'600px 0px'});RFU.observer.observe(sentinel);}if(window.RaikaPrivate?.authorized)rfuLoadMore({count:10});else document.addEventListener('raika:private-ready',()=>rfuLoadMore({count:10}),{once:true});rfuRender();}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',rfuInit);else rfuInit();}
window.RaikaFeedUI={init:rfuInit,loadMore:rfuLoadMore,surprise:rfuSurprise,getCard:rfuGetCard,markLocked:rfuMarkLocked,hide:rfuHide,insertAfter:rfuInsertAfter,showCardError:rfuShowCardError,getRecentSignatures:rfuRecentSignatures,render:rfuRender};
