const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'language-vocabulary.html'),'utf8');
const js=fs.readFileSync(path.join(root,'language-vocabulary.js'),'utf8');
const courtyardStylePath=path.join(root,'language-arabic-courtyard.css');
const ambiencePath=path.join(root,'language-ambience.js');

assert.ok(html.includes('id="arabic-living-moment"'),'Arabic page should include a living-language moment');
assert.ok(html.includes('id="language-music-toggle"'),'vocabulary page should include a shared music toggle');
assert.ok(html.includes('id="language-music-next"'),'vocabulary page should include a next-set control');
assert.ok(html.includes('language-ambience.js'),'vocabulary page should load the shared language ambience module');
assert.ok(js.includes("classList.toggle('arabic-vocabulary'"),'Arabic language selection should enable the courtyard theme');
assert.ok(fs.existsSync(courtyardStylePath),'Arabic vocabulary should have a dedicated courtyard stylesheet');
const css=fs.readFileSync(courtyardStylePath,'utf8');
assert.ok(css.includes('body.arabic-vocabulary'),'Arabic vocabulary should have a dedicated Levantine courtyard theme');
assert.ok(css.includes('.arabic-living-moment'),'Arabic living-language moment should be styled');
assert.ok(fs.existsSync(ambiencePath),'all vocabulary languages should share an ambience module');
const ambience=fs.readFileSync(ambiencePath,'utf8');
assert.ok(ambience.includes('language-arabic-courtyard.css'),'Arabic ambience should still load the courtyard stylesheet only for Arabic');
assert.ok(ambience.includes('my-center-language-music-muted'),'music preference should persist');
assert.ok(ambience.includes("id:'ar-1'")&&ambience.includes("id:'ar-2'")&&ambience.includes("id:'ar-3'"),'Arabic should have three music sets');
assert.ok(ambience.includes("id:'it-1'")&&ambience.includes("id:'it-2'")&&ambience.includes("id:'it-3'"),'Italian should have three music sets');
assert.ok(ambience.includes("id:'ru-1'")&&ambience.includes("id:'ru-2'")&&ambience.includes("id:'ru-3'"),'Russian should have three music sets');
assert.ok(ambience.includes("id:'es-1'")&&ambience.includes("id:'es-2'")&&ambience.includes("id:'es-3'"),'Spanish should have three music sets');
assert.ok(ambience.includes('عود')||ambience.includes('Oud'),'Arabic sets should prominently feature oud');
assert.ok(ambience.includes('music.volume=0.5'),'background music should default to half volume');
assert.ok(ambience.includes('new Audio('),'ambience should use real media recordings rather than synthesized oscillators');
assert.ok(ambience.includes('.loop=true'),'ambience recordings should loop');
assert.ok(!ambience.includes('createOscillator'),'ambience should not synthesize the background music');
assert.ok(ambience.includes('pointerdown'),'blocked autoplay should unlock on first interaction');
assert.ok(ambience.includes('language-music-toggle'),'ambience should expose a shared on/off control');
assert.ok(ambience.includes('language-music-next'),'ambience should expose a next-set control');
assert.ok(ambience.includes('صباح الخير'),'Arabic page should keep changing living-language content');
console.log('Language cultural ambience tests: OK');
