const assert = require('assert');
const feed = require('../language-feed-model.js');
assert.deepStrictEqual(feed.LANGUAGE_CODES, ['ar','it','ru','es']);
const mixed = feed.buildFeed({filter:'all', seed:'feed-a', count:16});
assert.strictEqual(mixed.length,16);
assert.deepStrictEqual(new Set(mixed.map(x=>x.lang)), new Set(['ar','it','ru','es']));
const onlyRu = feed.buildFeed({filter:'ru', seed:'feed-b', count:8});
assert.ok(onlyRu.every(x=>x.lang==='ru'));
const ar = feed.getDisplay({lang:'ar',target:'مرحبا',pron:'מַרְחַבַּא',he:'שלום'});
assert.strictEqual(ar.primary,'מַרְחַבַּא');
assert.strictEqual(ar.secondary,'مرحبا');
const ru = feed.getDisplay({lang:'ru',target:'привет',pron:'privet',he:'שלום'});
assert.strictEqual(ru.primary,'privet');
assert.strictEqual(ru.secondary,'привет');
const types = new Set(mixed.map(x=>x.type));
['word','sentence','joke','story','dialogue','challenge','culture'].forEach(t=>assert.ok(types.has(t)));
const changed = feed.buildFeed({filter:'all', seed:'feed-c', count:16});
assert.notDeepStrictEqual(changed.map(x=>x.id), mixed.map(x=>x.id));
console.log('language feed tests: OK');
