const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'language-vocabulary.html'),'utf8');
const js=fs.readFileSync(path.join(root,'language-vocabulary.js'),'utf8');
const courtyardStylePath=path.join(root,'language-arabic-courtyard.css');
const ambiencePath=path.join(root,'language-arabic-ambience.js');

assert.ok(html.includes('id="arabic-living-moment"'),'Arabic page should include a living-language moment');
assert.ok(html.includes('id="arabic-music-toggle"'),'Arabic page should include a music toggle');
assert.ok(html.includes('language-arabic-ambience.js'),'Arabic page should load its ambience module');
assert.ok(js.includes("classList.toggle('arabic-vocabulary'"),'Arabic language selection should enable the courtyard theme');
assert.ok(fs.existsSync(courtyardStylePath),'Arabic vocabulary should have a dedicated courtyard stylesheet');
const css=fs.readFileSync(courtyardStylePath,'utf8');
assert.ok(css.includes('body.arabic-vocabulary'),'Arabic vocabulary should have a dedicated Levantine courtyard theme');
assert.ok(css.includes('.arabic-living-moment'),'Arabic living-language moment should be styled');
assert.ok(css.includes('.arabic-music-toggle'),'Arabic music control should be styled');
assert.ok(fs.existsSync(ambiencePath),'Arabic vocabulary should have a dedicated ambience module');
const ambience=fs.readFileSync(ambiencePath,'utf8');
assert.ok(ambience.includes('language-arabic-courtyard.css'),'Arabic ambience should load the courtyard stylesheet only for Arabic');
assert.ok(ambience.includes('my-center-arabic-music-muted'),'music preference should persist');
assert.ok(ambience.includes('Solo_Oud_and_Ceramic_Darbuka_-_Arab_Instruments.webm'),'Arabic ambience should use a real oud and darbuka recording');
assert.ok(ambience.includes('upload.wikimedia.org'),'Arabic ambience should stream its licensed recording from Wikimedia Commons');
assert.ok(ambience.includes('new Audio('),'Arabic ambience should use a real media recording rather than synthesized oscillators');
assert.ok(ambience.includes('.loop=true'),'Arabic ambience recording should loop');
assert.ok(ambience.includes('Arab Instruments'),'Arabic ambience should retain source attribution');
assert.ok(ambience.includes('creativecommons.org/licenses/by/3.0'),'Arabic ambience should retain the CC BY 3.0 license link');
assert.ok(!ambience.includes('createOscillator'),'Arabic ambience should no longer synthesize the background music');
assert.ok(ambience.includes('pointerdown'),'blocked autoplay should unlock on first interaction');
assert.ok(ambience.includes('arabic-music-toggle'),'ambience should expose an on/off control');
assert.ok(ambience.includes('صباح الخير'),'Arabic page should have changing living-language content');
console.log('Arabic courtyard tests: OK');
