(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.RaishinDojoEffects=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const ATMOSPHERE_LIMITS={dust:36,petals:8,reducedDust:8};
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function axisTarget(value,center,deadZone,maxOffset){const delta=value-center;if(Math.abs(delta)<=deadZone)return 0;const amount=(Math.abs(delta)-deadZone)*0.12;return -Math.sign(delta)*Math.min(maxOffset,amount);}
function updateCamera(camera,player,dt,options={}){const centerX=options.centerX??800,centerY=options.centerY??650,deadZoneX=options.deadZoneX??180,deadZoneY=options.deadZoneY??90,maxX=options.maxX??48,maxY=options.maxY??28,followStrength=options.followStrength??6;dt=clamp(Number.isFinite(dt)?dt:0,0,.05);const targetX=axisTarget(player.x,centerX,deadZoneX,maxX),targetY=axisTarget(player.y,centerY,deadZoneY,maxY);if(targetX===0&&targetY===0&&camera.x===0&&camera.y===0)return{x:0,y:0};const alpha=1-Math.exp(-followStrength*dt);return{x:clamp(camera.x+(targetX-camera.x)*alpha,-maxX,maxX),y:clamp(camera.y+(targetY-camera.y)*alpha,-maxY,maxY)};}
function interactionFramingOffset(camera,interaction,strength=1){const maxX=1600*.04,maxY=900*.04,s=clamp(strength,0,1);return{x:clamp((800-interaction.x)*.05*s,-maxX,maxX),y:clamp((450-interaction.y)*.05*s,-maxY,maxY)};}
function backgroundRect(offset,scale=1.08,width=1600,height=900){scale=Math.max(1,Number(scale)||1);const w=width*scale,h=height*scale;return{x:(width-w)/2+(offset.x||0),y:(height-h)/2+(offset.y||0),width:w,height:h};}
function createAtmosphereState(reducedMotion=false){return{reducedMotion:!!reducedMotion,dust:[],petals:[]};}
function createDust(random,width,height){return{x:random()*width,y:random()*height,vx:(random()-.5)*8,vy:-2-random()*5,life:8+random()*8,size:.8+random()*1.8,alpha:.045+random()*.09};}
function createPetal(random,width){return{x:width*(.68+random()*.34),y:-18-random()*30,vx:-20-random()*28,vy:10+random()*18,life:10+random()*8,size:3+random()*3.5,rotation:random()*Math.PI*2,spin:(random()-.5)*1.2,alpha:.38+random()*.26};}
function particleAlive(p,width,height){return p.life>0&&p.x>-60&&p.x<width+60&&p.y>-60&&p.y<height+60;}
function updateAtmosphere(state,dt,options={}){const width=options.width??1600,height=options.height??900,random=options.random||Math.random,spawn=options.spawn!==false,reduced=!!state.reducedMotion;dt=clamp(Number.isFinite(dt)?dt:0,0,.05);let dust=(state.dust||[]).map(p=>({...p,x:p.x+p.vx*dt,y:p.y+p.vy*dt,life:p.life-dt})).filter(p=>particleAlive(p,width,height));let petals=reduced?[]:(state.petals||[]).map(p=>({...p,x:p.x+p.vx*dt,y:p.y+p.vy*dt,life:p.life-dt,rotation:p.rotation+p.spin*dt})).filter(p=>particleAlive(p,width,height));if(spawn){const dustTarget=reduced?Math.min(7,ATMOSPHERE_LIMITS.reducedDust):28;while(dust.length<dustTarget)dust.push(createDust(random,width,height));if(!reduced){const petalTarget=5;while(petals.length<petalTarget)petals.push(createPetal(random,width));}}return{reducedMotion:reduced,dust:dust.slice(0,reduced?ATMOSPHERE_LIMITS.reducedDust:ATMOSPHERE_LIMITS.dust),petals:reduced?[]:petals.slice(0,ATMOSPHERE_LIMITS.petals)};}
function lightPulse(timeMs){return .07+Math.sin((Number(timeMs)||0)*.0008)*.015;}
function renderAtmosphere(ctx,state,offset={x:0,y:0}){if(!ctx||!state)return;ctx.save();for(const p of state.dust){ctx.beginPath();ctx.fillStyle=`rgba(255,239,199,${p.alpha})`;ctx.arc(p.x+offset.x*.2,p.y+offset.y*.15,p.size,0,Math.PI*2);ctx.fill();}for(const p of state.petals){ctx.save();ctx.translate(p.x+offset.x*.45,p.y+offset.y*.35);ctx.rotate(p.rotation);ctx.fillStyle=`rgba(247,186,192,${p.alpha})`;ctx.beginPath();ctx.ellipse(0,0,p.size,p.size*.45,0,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.restore();}
function drawFloorContact(ctx,x,y,scale=1){if(!ctx)return;ctx.save();const g=ctx.createRadialGradient(x,y,2,x,y,52*scale);g.addColorStop(0,'rgba(245,207,128,.10)');g.addColorStop(.5,'rgba(30,19,10,.17)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(x,y,58*scale,18*scale,0,0,Math.PI*2);ctx.fill();ctx.restore();}
return{ATMOSPHERE_LIMITS,updateCamera,interactionFramingOffset,backgroundRect,createAtmosphereState,updateAtmosphere,lightPulse,renderAtmosphere,drawFloorContact};
});
