const fs=require('fs');
const assert=require('assert');
const index=fs.readFileSync(__dirname+'/index.html','utf8');
['score-timer-v2-core.js?v=1','score-games-core.js?v=1','score-games-rules-v2.js?v=1','score-custom-rules-v2.js?v=1','score-games-ui.js?v=2','score-advanced-ui-v2.js?v=1','score-games.css?v=1','score-advanced-ui-v2.css?v=1','score-tools-v2.js?v=1','score-tools-v2.css?v=1'].forEach(x=>assert(index.includes(x),`missing ${x}`));
assert(index.indexOf('score-live-patch.js?v=8') < index.indexOf('score-timer-v2-core.js?v=1'),'V2 timer core must load after existing patch');
assert(index.indexOf('score-timer-v2-core.js?v=1') < index.indexOf('score-games-core.js?v=1'),'timer core must load before game core');
assert(index.indexOf('score-games-core.js?v=1') < index.indexOf('score-games-rules-v2.js?v=1'),'base game core must load before advanced rules');
assert(index.indexOf('score-games-rules-v2.js?v=1') < index.indexOf('score-custom-rules-v2.js?v=1'),'advanced rules must load before custom rule extension');
assert(index.indexOf('score-custom-rules-v2.js?v=1') < index.indexOf('score-games-ui.js?v=2'),'all game rules must load before V2 UI');
assert(index.indexOf('score-games-ui.js?v=2') < index.indexOf('score-advanced-ui-v2.js?v=1'),'advanced configuration must enhance the main UI');
assert(index.indexOf('score-advanced-ui-v2.js?v=1') < index.indexOf('score-tools-v2.js?v=1'),'field tools must load after advanced configuration');
console.log('index v2 contract passed');
