(function(){
  'use strict';
  const HISTORY='teamScoreSpiegel.history';
  let undoStack=[],menuPlayer=null,longTimer=0,suppressClick=false,dragId=null,finalDuelAnnounced=false;
  const ERRORS=[['reception','Reception error'],['dropped','Ball dropped'],['out','Out'],['double','Double contact'],['net','Net error'],['serve','Serve error'],['other','Other']];
  function suite(){return window.TeamScoreGameSuite||null}
  function session(){const s=suite();return s&&s.getSession?s.getSession():null}
  function active(){const s=session();return !!(s&&s.mode==='spiegel')}
  function announce(text,p){const s=suite();if(s&&s.announcer)s.announcer.say(text,p||'normal')}
  function saveSession(){const s=session();if(s)try{localStorage.setItem('teamScoreSuite.session',JSON.stringify(s))}catch(_){}}
  function optionsKey(){const s=session();return'teamScoreSpiegel.'+(s?s.id:'none')+'.options'}
  function options(){try{return Object.assign({behavior:'out'},JSON.parse(localStorage.getItem(optionsKey())||'')||{})}catch(_){return{behavior:'out'}}}
  function saveOptions(panel){const o={behavior:panel.querySelector('[data-sp-behavior]')?.value||'out'};try{localStorage.setItem(optionsKey(),JSON.stringify(o))}catch(_){}return o}
  function players(){const s=session();return s&&s.state&&Array.isArray(s.state.players)?s.state.players:[]}
  function meta(){const s=session();if(!s)return{};s.state=s.state||{};s.state.spiegelMeta=s.state.spiegelMeta||{};for(const p of players())if(!s.state.spiegelMeta[p.id])s.state.spiegelMeta[p.id]={errors:{},plays:0,cleanStreak:0,bestCleanStreak:0,riskCount:0,placement:null,reachedFinalDuel:false,finalLife:false};return s.state.spiegelMeta}
  function alive(){return players().filter(p=>!p.eliminated).sort((a,b)=>(a.order||0)-(b.order||0))}
  function current(){return alive()[0]||null}
  function next(){return alive()[1]||null}
  function threshold(){const s=session();return Number(s&&s.config&&s.config.eliminationThreshold||5)}
  function snapshot(){return{players:JSON.parse(JSON.stringify(players())),meta:JSON.parse(JSON.stringify(meta()))}}
  function pushUndo(){undoStack.push(snapshot());if(undoStack.length>30)undoStack.shift()}
  function restoreSnapshot(x){const s=session();if(!s||!x)return;s.state.players=x.players;s.state.spiegelMeta=x.meta;saveSession();render()}
  function undo(){restoreSnapshot(undoStack.pop())}
  function commonError(m){const entries=Object.entries(m.errors||{}).sort((a,b)=>b[1]-a[1]);if(!entries.length||!entries[0][1])return'—';return ERRORS.find(x=>x[0]===entries[0][0])?.[1]||entries[0][0]}
  function moveToEnd(p){const all=players(),max=Math.max(0,...all.map(x=>Number(x.order)||0));p.order=max+1}
  function eliminate(p,m){const before=alive().length;p.eliminated=true;m.placement=before;announce(`${p.name}. Eliminated.`,'high')}
  function checkFinalDuel(){const a=alive(),mm=meta();if(a.length===2){a.forEach(p=>mm[p.id].reachedFinalDuel=true);if(!finalDuelAnnounced){finalDuelAnnounced=true;announce('Final Duel. Final two.','high')}}if(a.length===1){mm[a[0].id].placement=1;announce(`Last player standing. ${a[0].name}.`,'finish')}}
  function addBadPoint(id,type){const p=players().find(x=>x.id===id);if(!p||p.eliminated)return;pushUndo();const mm=meta(),m=mm[id],t=threshold(),behavior=options().behavior;m.plays++;m.errors[type]=(m.errors[type]||0)+1;m.cleanStreak=0;p.badPoints=(p.badPoints||0)+1;if(current()?.id===id)session().state.spiegelTurnHadError=true;
    if(behavior==='final-life'&&m.finalLife){eliminate(p,m)}else if(p.badPoints>=t){if(behavior==='out')eliminate(p,m);else if(behavior==='queue'){moveToEnd(p);announce(`${p.name}. Penalty. End of queue.`,'normal')}else if(behavior==='reset'){p.badPoints=0;moveToEnd(p);announce(`${p.name}. Reset to zero.`,'normal')}else if(behavior==='final-life'){m.finalLife=true;p.badPoints=Math.max(0,t-1);m.riskCount++;announce(`${p.name}. Final life.`,'high')}}else if(p.badPoints===t-1){m.riskCount++;announce(`${p.name}. One bad point from elimination.`,'high')}
    saveSession();checkFinalDuel();render()}
  function rotate(){const p=current();if(!p)return;pushUndo();const m=meta()[p.id];if(!session().state.spiegelTurnHadError){m.cleanStreak++;m.bestCleanStreak=Math.max(m.bestCleanStreak,m.cleanStreak)}else m.cleanStreak=0;session().state.spiegelTurnHadError=false;moveToEnd(p);saveSession();const n=current();if(n)announce(`Next player. ${n.name}.`,'normal');render()}
  function restorePlayer(id){const p=players().find(x=>x.id===id);if(!p)return;pushUndo();p.eliminated=false;p.badPoints=Math.max(0,threshold()-1);const m=meta()[id];m.placement=null;m.finalLife=false;moveToEnd(p);finalDuelAnnounced=false;saveSession();render()}
  function setErrorMenu(id){menuPlayer=id;render()}
  function errorMenuHtml(){if(!menuPlayer)return'';const p=players().find(x=>x.id===menuPlayer);if(!p)return'';return`<div class="score-sp-error-menu"><div><strong>${p.name} — error type</strong><button data-sp-menu-close>✕</button></div><div>${ERRORS.map(([id,label])=>`<button data-sp-error="${id}" data-player="${p.id}">${label}</button>`).join('')}</div></div>`}
  function previousFor(name){try{const h=JSON.parse(localStorage.getItem(HISTORY)||'[]');for(const game of h){const x=(game.players||[]).find(p=>p.name===name);if(x)return x}}catch(_){}return null}
  function improvement(p){const prev=previousFor(p.name);return prev?Number(prev.badPoints||0)-Number(p.badPoints||0):null}
  function mostImproved(){let best=null;for(const p of players()){const d=improvement(p);if(d!=null&&(!best||d>best.delta))best={name:p.name,delta:d}}return best&&best.delta>0?`${best.name} (+${best.delta})`:'—'}
  function playerCard(p,index){const m=meta()[p.id],isNow=current()?.id===p.id,isNext=next()?.id===p.id,err=commonError(m);return`<article class="score-sp-player ${p.eliminated?'out':''} ${isNow?'now':''}" draggable="true" data-sp-drag="${p.id}"><div class="score-sp-player-top"><span>${isNow?'NOW':isNext?'NEXT':'#'+(index+1)}</span><strong>${p.name}</strong>${m.finalLife?'<em>Final life</em>':''}</div><button class="score-sp-bad" data-sp-bad="${p.id}" ${p.eliminated?'disabled':''}><b>${p.badPoints||0}</b><small>bad point · tap / long press</small></button><div class="score-sp-stats"><span>Most: ${err}</span><span>Clean best: ${m.bestCleanStreak}</span><span>Risk: ${m.riskCount}</span></div>${p.eliminated?`<button data-sp-restore="${p.id}">Restore</button>`:''}</article>`}
  function finalStatsHtml(){const a=alive();if(a.length>1)return'';const ordered=players().slice().sort((x,y)=>{const mx=meta()[x.id],my=meta()[y.id];return(Number(mx.placement)||99)-(Number(my.placement)||99)});return`<section class="score-sp-final"><strong>Game Summary</strong>${ordered.map(p=>{const m=meta()[p.id];return`<div><b>${m.placement?'#'+m.placement:'—'} ${p.name}</b><span>${p.badPoints||0} bad · ${commonError(m)} · Best clean ${m.bestCleanStreak} · Risk ${m.riskCount}${m.reachedFinalDuel?' · Final Duel':''}</span></div>`}).join('')}<p>Most Improved: ${mostImproved()}</p></section>`}
  function render(){if(!active())return;const p=document.querySelector('.score-suite-active-game');if(!p)return;const a=alive(),cur=current(),nxt=next(),king=players().filter(x=>!x.eliminated).slice().sort((x,y)=>(x.badPoints||0)-(y.badPoints||0))[0];p.innerHTML=`<div class="score-suite-sheet-head"><strong>שפיגל / מלך התחתיות</strong><button data-close>✕</button></div><section class="score-sp-hud"><div class="score-sp-kicker">SPIEGEL · BAD POINTS</div><div class="score-sp-turn"><div><small>Now Playing</small><strong>${cur?.name||'—'}</strong></div><div><small>Next</small><strong>${nxt?.name||'—'}</strong></div><div><small>King</small><strong>${king?.name||'—'}</strong></div></div><div class="score-sp-rule">Elimination at ${threshold()} · ${options().behavior} ${a.length===2?'· Final Duel':''}</div></section><div class="score-sp-grid">${players().slice().sort((x,y)=>(x.order||0)-(y.order||0)).map(playerCard).join('')}</div><div class="score-sp-actions"><button data-sp-next>Next</button><button data-sp-undo ${undoStack.length?'':'disabled'}>Undo</button><button data-end>Finish</button></div>${finalStatsHtml()}${errorMenuHtml()}`;bindDrag(p)}
  function bindDrag(panel){panel.querySelectorAll('[data-sp-drag]').forEach(el=>{el.addEventListener('dragstart',()=>{dragId=el.dataset.spDrag});el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const target=el.dataset.spDrag;if(!dragId||dragId===target)return;pushUndo();const ps=players().slice().sort((a,b)=>(a.order||0)-(b.order||0)),from=ps.findIndex(x=>x.id===dragId),to=ps.findIndex(x=>x.id===target);const [moved]=ps.splice(from,1);ps.splice(to,0,moved);ps.forEach((x,i)=>x.order=i);saveSession();render()})})}
  function decorateSetup(){if(!active())return;const p=document.querySelector('.score-suite-active');if(!p||p.querySelector('.score-sp-setup'))return;const o=options(),b=document.createElement('section');b.className='score-sp-setup';b.innerHTML=`<strong>👑 Spiegel settings</strong><label>At threshold<select data-sp-behavior><option value="out" ${o.behavior==='out'?'selected':''}>Eliminate</option><option value="queue" ${o.behavior==='queue'?'selected':''}>End of queue + penalty</option><option value="reset" ${o.behavior==='reset'?'selected':''}>Restart at 0</option><option value="final-life" ${o.behavior==='final-life'?'selected':''}>Final life before elimination</option></select></label><small>Tap = +1 bad point · long press = choose error type · drag cards to reorder.</small>`;p.querySelector('.score-suite-form')?.after(b)}
  function activate(){meta();session().state.spiegelTurnHadError=false;saveSession();render()}
  function saveHistory(){const game={at:new Date().toISOString(),players:players().map(p=>{const m=meta()[p.id];return{name:p.name,badPoints:p.badPoints||0,commonError:commonError(m),bestCleanStreak:m.bestCleanStreak,riskCount:m.riskCount,placement:m.placement,reachedFinalDuel:m.reachedFinalDuel}})};let h=[];try{h=JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch(_){}h.unshift(game);try{localStorage.setItem(HISTORY,JSON.stringify(h.slice(0,50)))}catch(_){}}
  document.addEventListener('pointerdown',e=>{if(!active())return;const b=e.target.closest('[data-sp-bad]');if(!b)return;clearTimeout(longTimer);suppressClick=false;longTimer=setTimeout(()=>{suppressClick=true;setErrorMenu(b.dataset.spBad)},550)},true)
  document.addEventListener('pointerup',()=>clearTimeout(longTimer),true);document.addEventListener('pointercancel',()=>clearTimeout(longTimer),true)
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-begin')&&b.closest('.score-suite-active')&&active()){saveOptions(b.closest('.score-suite-active'));setTimeout(activate,40);return}if(!active())return;if(b.dataset.spBad){e.preventDefault();e.stopImmediatePropagation();if(suppressClick){suppressClick=false;return}addBadPoint(b.dataset.spBad,'other');return}if(b.dataset.spError){e.preventDefault();e.stopImmediatePropagation();menuPlayer=null;addBadPoint(b.dataset.player,b.dataset.spError);return}if(b.hasAttribute('data-sp-menu-close')){e.preventDefault();e.stopImmediatePropagation();menuPlayer=null;render();return}if(b.hasAttribute('data-sp-next')){e.preventDefault();e.stopImmediatePropagation();rotate();return}if(b.hasAttribute('data-sp-undo')){e.preventDefault();e.stopImmediatePropagation();undo();return}if(b.dataset.spRestore){e.preventDefault();e.stopImmediatePropagation();restorePlayer(b.dataset.spRestore);return}if(b.hasAttribute('data-end'))saveHistory()},true)
  function poll(){if(active()){decorateSetup();if(document.querySelector('.score-suite-active-game'))render()}}
  setInterval(poll,450);
  window.TeamScoreSpiegel={render,addBadPoint,rotate,restorePlayer,undo,getPlayers:players,getMeta:meta};
})();