const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = __dirname;
const read = name => fs.readFileSync(path.join(root, name), 'utf8');

const js = read('score-live-patch.js');
const css = read('score-live-patch.css');
const leader = read('score-leader-top.js');
const index = read('index.html');
const containJsPath = path.join(root, 'score-image-contain.js');
const containCssPath = path.join(root, 'score-image-contain.css');
const surfaceJsPath = path.join(root, 'score-card-surface.js');
const surfaceCssPath = path.join(root, 'score-card-surface.css');
const lowerJsPath = path.join(root, 'score-layout-lower.js');

assert(!/score-final-column/.test(js.replace(/remove\(['"]score-final-column['"]\)/g, '')), 'patch must not force the legacy one-column class');
assert(/classList\.remove\(['"]score-final-column['"]\)/.test(js), 'patch must remove the forced one-column class');
assert(/layoutObserver\.observe\(teams,\{childList:true\}\)/.test(js), 'layout observer must watch child changes only');
assert(!/attributeFilter:\['class'\]/.test(js), 'layout observer must not watch class mutations and fight the legacy script');
assert(/syncTwoColumnFit/.test(js) && /score-two-column-fit/.test(js), 'base patch must keep two-column detection');
assert(/#teams\.score-two-column-fit/.test(css) && /grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/.test(css), 'base two-column mode must use two equal tracks');
assert(fs.existsSync(containJsPath), 'two-column image containment script must exist');
assert(fs.existsSync(containCssPath), 'two-column image containment stylesheet must exist');
const containJs = read('score-image-contain.js');
const containCss = read('score-image-contain.css');
assert(/#sharpBg img\.active/.test(containJs), 'containment must measure the active sharp image rather than the full-screen wrapper');
assert(/visibleImageRect/.test(containJs), 'containment must calculate the painted object-fit image bounds');
assert(/score-image-contained/.test(containJs), 'containment must mark the two-column layout after measuring the image');
assert(/--score-image-width/.test(containJs) && /--score-image-shift/.test(containJs), 'containment must set image width and horizontal alignment variables');
assert(/#teams\.score-two-column-fit\.score-image-contained/.test(containCss), 'containment CSS must only affect two-column mode');
assert(/translateX\(var\(--score-image-shift/.test(containCss), 'contained two-column grid must align itself to the visible image center');
assert(/\.score-board-row/.test(containCss) && /grid-template-columns/.test(containCss), 'contained mobile cards must compact score controls to fit the image');
assert(/body\.projection-mode #teams \.score-board-row/.test(css), 'projection mode must explicitly restore the score row layout');
assert(/body\.projection-mode #teams \.score-board-row[\s\S]*grid-template-columns:46px minmax\(48px,max-content\) 46px!important/.test(css), 'projection mode must keep minus, score and plus in one horizontal grid row');
assert(/body\.projection-mode #teams \.score-board-row > button/.test(css), 'projection mode must reset score buttons inside the row');
assert(/body\.projection-mode #teams \.score-board-value/.test(css), 'projection mode must reset the score value inside the row');
const projectionCardStart='body.projection-mode #teams > .card.score-card-professional{';
const projectionCardIndex=css.indexOf(projectionCardStart);
assert(projectionCardIndex>=0, 'projection mode must have an explicit professional-card override');
const projectionCardRule=css.slice(projectionCardIndex, css.indexOf('\n}', projectionCardIndex)+2);
assert(projectionCardRule.includes('transform:none!important'), 'projection mode must neutralize the legacy card scale transform');
assert(/--score-width/.test(css) && /syncScoreBoxWidths/.test(js), 'score box width must respond to the rendered score digits');
assert(/margin:0 auto!important/.test(css), 'score cards must stay centered inside their layout column/image area');
assert(/markRankOutside/.test(js) && /score-rank-outside/.test(js), 'rank badge must be detected and moved outside the gray card flow');
assert(/\.score-rank-outside/.test(css) && /position:absolute!important/.test(css) && /top:calc\(100% \+ 12px\)/.test(css), 'rank badge must render below the gray card');
assert(/markTeamNameTop/.test(js) && /score-team-name-top/.test(js), 'team name must be marked for top-right placement');
assert(/\.score-team-name-top/.test(css) && /top:7px!important/.test(css) && /right:12px!important/.test(css), 'team name must sit against the card ceiling on the right');
assert(/aspect-ratio:auto!important/.test(css), 'professional score cards must not keep a square aspect ratio');
assert(/height:max-content!important/.test(css), 'gray score card height must collapse to its content');
assert(/padding:34px 14px 6px!important/.test(css), 'desktop gray card must reserve only a small header strip and end after mega');
assert(/padding:32px 12px 6px!important/.test(css), 'mobile gray card must reserve only a small header strip and end after mega');
assert(fs.existsSync(surfaceJsPath), 'card surface behavior layer must exist');
assert(fs.existsSync(surfaceCssPath), 'card surface stylesheet must exist');
const surfaceJs = read('score-card-surface.js');
const surfaceCss = read('score-card-surface.css');
assert(/tightenCardsToMega/.test(surfaceJs) && /CARD_MEGA_BOTTOM_GAP_PX\s*=\s*6/.test(surfaceJs), 'card must end almost immediately below the mega button');
assert(/--score-card-tight-height/.test(surfaceJs) && /--score-card-tight-height/.test(surfaceCss), 'measured tight card height must drive the rendered card height');
assert(/markTeamColorCards/.test(surfaceJs) && /--score-team-rgb/.test(surfaceJs), 'every team card must derive its tint from the team color');
assert(/score-card-team-tint/.test(surfaceJs) && /\.score-card-team-tint/.test(surfaceCss), 'team tint class must apply to all detected team colors');
assert(/rgba\(var\(--score-team-rgb\),\s*0\.1[0-9]\)/.test(surfaceCss), 'team card tint must remain very light and translucent');
assert(/backdrop-filter:blur/.test(surfaceCss), 'translucent team card must preserve visible background imagery');
assert(!/score-card-tint-blue/.test(surfaceCss), 'surface styling must no longer be blue-only');
assert(/surfaceLayoutObserver/.test(surfaceJs) && /attributeFilter:\s*\['data-score-layout-mode'\]/.test(surfaceJs), 'surface refresh must react directly to layout mode changes');
assert(/surfaceProjectionObserver/.test(surfaceJs) && /surfaceProjectionObserver\.observe\(document\.body,\{attributes:true,attributeFilter:\['class'\]\}\)/.test(surfaceJs), 'surface refresh must react directly to projection mode changes');
assert(fs.existsSync(lowerJsPath), 'image-relative layout positioning script must exist');
const lowerJs = read('score-layout-lower.js');
assert(/FIRST_ROW_IMAGE_OFFSET_PX\s*=\s*135/.test(lowerJs), 'first score row must align around 135px from the visible image top');
assert(!/findHeaderBottom/.test(lowerJs), 'first-row positioning must not depend on the TeamScore header bottom');
assert(!/measureCardGap/.test(lowerJs), 'first-row positioning must not reserve a full card-height spacer');
assert(/image\.top\s*\+\s*FIRST_ROW_IMAGE_OFFSET_PX/.test(lowerJs), 'first-row top must derive from the visible image top plus the requested offset');
assert(/score-layout-free/.test(lowerJs), 'image-relative positioning must also cover free layout mode');
assert(/--score-layout-top/.test(lowerJs) && /--score-layout-height/.test(lowerJs), 'lower layout script must update both layout top and remaining height');
assert(/data-score-layout-mode/.test(lowerJs) && /projection-mode/.test(lowerJs), 'lower layout positioning must react to layout and projection mode changes');
assert(/#sharpBg img\.active/.test(lowerJs), 'lower layout positioning must derive its bounds from the visible foreground image');
assert(/bar\.addEventListener\(['"]pointerdown['"]/.test(js), 'timer shell must be draggable without a visible move icon');
assert(!/⠿/.test(js), 'timer must not render the move icon');
assert(!/↘/.test(js), 'timer must not render the resize icon');
assert(/score-timer-resize-zone/.test(js) && /resizePointer/.test(js) && /TIMER_MAX_SCALE/.test(js), 'timer must keep an invisible resize zone');
assert(/\.score-timer-resize-zone/.test(css) && /opacity\s*:\s*0/.test(css), 'resize zone must stay visually hidden');
assert(/smallestMatch/.test(js) && /TeamScore/.test(js) && /ספירת נקודות לקבוצות/.test(js), 'header offset must find nested title/subtitle text');
assert(/score-header-shift-left/.test(js) && /\.score-header-shift-left/.test(css) && /left:-24px/.test(css), 'mobile header text must visibly move 24px left');
assert(!/timerObserver/.test(js) && !/scoreObserver/.test(js), 'patch must not run whole-page observers after interactions');
assert(!/MutationObserver/.test(leader), 'leader banner must not use a whole-page mutation observer');
assert(/document\.body\.appendChild\(banner\)/.test(leader), 'leader banner must be portaled directly under body so top zero is viewport-relative');
assert(/findLeaderVisualTop/.test(leader), 'leader script must measure the actual visible leader text rather than only the wrapper');
assert(/visualOffset/.test(leader) && /-visualOffset/.test(leader), 'leader wrapper must compensate for its internal top gap');
assert(/scoreLeaderVisualOffset/.test(leader), 'measured leader visual offset must be recorded for regression/debugging');
assert(/findImageCenterX/.test(leader), 'leader must calculate the active image horizontal center');
assert(/#sharpBg img\.active/.test(leader), 'leader must center against the active foreground image');
assert(/findLeaderBanners/.test(leader) && /hideDuplicateLeaderBanners/.test(leader), 'leader script must detect and hide duplicate leader blocks');
assert(/scoreLeaderDuplicate/.test(leader), 'duplicate leader blocks must be marked for reliable hiding/restoration');
assert(!/isDoubleProjection/.test(leader), 'the single top leader must remain visible in double projection mode');
assert(/translateX\(-50%\)/.test(leader), 'top leader must center from its own midpoint');
assert(/score-live-patch\.css\?v=10/.test(index), 'index must preserve the current base patch stylesheet');
assert(/score-live-patch\.js\?v=8/.test(index), 'index must preserve the current base patch script');
assert(/score-card-surface\.css\?v=2/.test(index), 'index must load the current team-color surface stylesheet');
assert(/score-card-surface\.js\?v=3/.test(index), 'index must load the all-layout surface refresh script');
assert(/score-layout-lower\.js\?v=4/.test(index), 'index must load the gray-rectangle-aligned lower layout script');
assert(/score-image-contain\.css\?v=1/.test(index), 'index must load the image containment stylesheet');
assert(/score-image-contain\.js\?v=1/.test(index), 'index must load the image containment script');
assert(/score-leader-top\.js\?v=9/.test(index), 'index must load the single-top-leader version');
assert(index.indexOf('score-layout-menu.js?v=1') < index.indexOf('score-layout-lower.js?v=4'), 'image-relative positioning must load after the layout controller');
assert(index.indexOf('score-card-surface.js?v=3') < index.indexOf('score-layout-lower.js?v=4'), 'image-relative positioning must load after surface sizing');
assert(index.indexOf('score-live-patch.js?v=8') < index.indexOf('score-card-surface.js?v=3'), 'surface behavior must load after the base score patch');
console.log('score-live regression checks passed');
